services:
  web:
    build: .
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    ports:
      - "8501:8501"
    volumes:
      - ./tests:/app/tests
    entrypoint: ["streamlit", "run", "src/app.py"]

  agent:
    build: .
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    volumes:
      - ./tests:/app/tests
    entrypoint: ["python", "src/run.py"]
